"""Offline browser of the measured full-model execution DAG."""
import argparse,base64,gzip,json
from pathlib import Path
HTML='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>P3a · 独立推理任务</title><style>
body{margin:0;background:#f0f4f5;color:#193740;font:15px/1.65 system-ui,sans-serif}main{max-width:1250px;margin:auto;padding:24px}h1{font-size:29px}h2{font-size:20px}section{background:white;border:1px solid #d5dfe2;border-radius:9px;padding:18px;margin:20px 0}.note{border-left:4px solid #bf872b;background:#fff3da;padding:14px}select{font:inherit;padding:7px;margin:6px;max-width:100%}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;white-space:nowrap}td,th{padding:8px;text-align:left;border-bottom:1px solid #d7e2e4}pre{white-space:pre-wrap;overflow:auto;max-height:420px;background:#f2f6f6;padding:15px;font-size:12px}.kernel{cursor:pointer}.kernel:hover{stroke:#111;stroke-width:2}.bad{color:#a13d2d}small{color:#526d75}a{color:#187e83}svg{display:block}</style>
<main><small>PRACTICE 23 · ASCEND 910B2C · QWEN2.5-0.5B · BF16 · EAGER</small><h1>两个独立 forward：串行、双流与 batch=2</h1><p>完整预训练模型，单 CPU 提交线程；共享只读权重，输入与可变 KV 独立。每个任务执行一次 forward，decode 的前缀准备不计时。</p><p class="note">这是 HuggingFace 执行 harness，不是 vLLM 请求调度或端到端服务。1024-token prefill 的 batch=2 未通过预设数值容差，其耗时不作为有效收益结论。图恢复 stream/event 执行顺序与任务边界，尚未恢复所有 kernel 内部访存。</p>
<section><h2>实验与设备证据</h2><label>形状<select id="case"></select></label><label>模式<select id="mode"><option value="serial">serial · 同流</option><option value="parallel">parallel · 双流</option><option value="batch">batch=2</option></select></label><label>重复<select id="repeat"></select></label><p id="stats"></p><div class="scroll" id="dag"></div><small>绿色为任务 A，蓝色为任务 B，紫色为 batch。两个任务没有跨任务数据依赖；串行模式增加同流 FIFO 顺序，双流分别等待输入就绪并在各自结束后由主机汇合。batch kernel 同时服务两行，不能拆成 A/B 两条 kernel 链。</small></section>
<section><h2>逐 kernel 设备时间线</h2><label>缩放<select id="zoom"><option>1</option><option>10</option><option>50</option></select></label><label>连线<select id="edges"><option value="event_wait">event wait</option><option value="stream_order">stream FIFO</option><option value="">隐藏</option></select></label><div class="scroll" id="timeline"></div><small>横轴相对 µs，矩形宽度为真实计算时长；灰色菱形表示非计算设备任务。重叠按两个任务实际计算区间的并集求交，不使用 forward 包围跨度。仅有 API 证据的等待保存在完整图中，不画成设备任务。</small></section>
<section><h2>所选 kernel 与依赖证据</h2><pre id="details">点击时间线中的 kernel。</pre></section>
<section><h2>无 profiler 性能</h2><div class="scroll" id="performance"></div><small>单位 ms/pair，中位数；12 次重复、轮换模式和 AB/BA 提交顺序。就绪时间来自公共起始 NPU event 至各任务末尾 event，包含主机提交供给不足造成的空闲。吞吐只针对此 forward 工作单元。</small></section>
<section><h2>完成时间与额外显存</h2><div class="scroll" id="memory"></div><small>first/last 为两任务较早/较晚的设备就绪时间；batch 两任务同时就绪。增量峰值为计时开始后的 allocated 增长，不含准备好的输入、decode KV、权重和 allocator reserved。全部原始记录另含绝对峰值。</small></section>
<p><a href="../RESULTS.md">结果、失败项与边界</a> · <a href="../results/published/execution_graph.json.gz">完整执行图 gzip</a></p></main>
<script>(async()=>{const packed=Uint8Array.from(atob("__DATA__"),c=>c.charCodeAt(0));const D=JSON.parse(await new Response(new Blob([packed]).stream().pipeThrough(new DecompressionStream("gzip"))).text()), $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const colors={A:'#208678',B:'#357dba',AB:'#8a61ab'},nodes=Object.fromEntries(D.nodes.map(n=>[n.id,n]));let trial;
function options(id,xs){$(id).innerHTML=xs.map(x=>`<option>${esc(x)}</option>`).join('')}
function init(){trial=D.summary.trials.find(t=>t.case==$('case').value&&t.mode==$('mode').value&&t.repeat==$('repeat').value);if(!trial)return;$('details').textContent='点击当前实验时间线中的 kernel。';let invalid=D.summary.invalid_cells.includes(trial.case+'/'+trial.mode);$('stats').className=invalid?'bad':'';$('stats').textContent=`${trial.compute_tasks} 个计算任务 · stream ${trial.streams.join('/')} · A/B 计算重叠 ${trial.overlap_us.toFixed(3)} µs · ${invalid?'数值未通过':'数值通过'}`;dag();timeline()}
function dag(){let s='<svg width="1030" height="190"><defs><marker id="arr" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0 0L7 3L0 6" fill="#768c92"/></marker></defs>';let pos=trial.mode==='batch'?{ready:[10,65],AB:[355,65],join:[785,65]}:{ready:[10,65],A:[355,10],B:[355,115],join:[785,65]};let labels={ready:'输入 / 独立 KV 已就绪',A:'完整 forward A',B:'完整 forward B',AB:'完整 forward · batch=2',join:'主机等待末尾 events'};for(let n of trial.mode==='batch'?['AB']:['A','B'])for(let [a,b] of [['ready',n],[n,'join']])s+=`<path d="M${pos[a][0]+220} ${pos[a][1]+25}L${pos[b][0]} ${pos[b][1]+25}" stroke="#768c92" fill="none" marker-end="url(#arr)"/>`;if(trial.mode==='serial'){let [a,b]=trial.order;s+=`<path d="M600 ${pos[a][1]+25}L660 ${pos[a][1]+25}L660 ${pos[b][1]+25}L600 ${pos[b][1]+25}" stroke="#c28335" stroke-dasharray="5 3" fill="none" marker-end="url(#arr)"/><text x="675" y="100" font-size="12">FIFO ${a}→${b}</text>`}for(let [n,[x,y]] of Object.entries(pos))s+=`<rect x="${x}" y="${y}" width="220" height="50" rx="5" fill="${colors[n]||'#57717c'}"/><text x="${x+10}" y="${y+31}" fill="white" font-size="14">${labels[n]}</text>`;$('dag').innerHTML=s+'</svg>'}
function timeline(){let ts=trial.node_ids.map(id=>nodes[id]),streams=[...new Set(ts.map(t=>t.stream))].sort(),lo=Math.min(...ts.map(t=>Number(t.start_us))),hi=Math.max(...ts.map(t=>Number(t.end_us))),span=hi-lo,width=1200*Number($('zoom').value),height=100+streams.length*90,coords={},s=`<svg width="${width}" height="${height}">`;for(let [i,st] of streams.entries())s+=`<text x="0" y="${65+i*90}" font-size="12">stream ${st}</text><line x1="95" x2="${width-25}" y1="${85+i*90}" y2="${85+i*90}" stroke="#dae4e6"/>`;for(let t of ts)coords[t.id]=[95+(Number(t.start_us)-lo)/span*(width-120),45+streams.indexOf(t.stream)*90+(t.is_compute?0:40),Number(t.duration_us)/span*(width-120)];for(let e of D.edges){if(e.kind!==$('edges').value||!coords[e.source]||!coords[e.target])continue;let a=coords[e.source],b=coords[e.target];s+=`<path d="M${a[0]+a[2]} ${a[1]+15}Q${b[0]} ${b[1]-20} ${b[0]} ${b[1]+15}" stroke="#997ba6" stroke-width=".8" fill="none" opacity=".6"/>`}for(let t of ts){let [x,y,w]=coords[t.id],title=esc(t.name+' · '+t.duration_us+' µs · '+(t.task||t.role||t.stage));s+=t.is_compute?`<rect class="kernel" data-node="${t.id}" x="${x}" y="${y}" width="${w}" height="30" fill="${colors[t.task]||'#82999b'}"><title>${title}</title></rect>`:`<path class="kernel" data-node="${t.id}" d="M${x} ${y+10}l4 5l-4 5l-4 -5Z" fill="#6d8286"><title>${title}</title></path>`}s+=`<text x="95" y="${height-10}" font-size="12">0 µs</text><text x="${width-140}" y="${height-10}" font-size="12">${span.toFixed(2)} µs</text></svg>`;$('timeline').innerHTML=s;document.querySelectorAll('[data-node]').forEach(e=>e.onclick=()=>{$('details').textContent=JSON.stringify({node:nodes[e.dataset.node],edges:D.edges.filter(x=>x.source===e.dataset.node||x.target===e.dataset.node),requirements:D.requirements.filter(x=>x.source===e.dataset.node||x.target===e.dataset.node)},null,2)})}
options('case',[...new Set(D.summary.trials.map(t=>t.case))]);options('repeat',[...new Set(D.summary.trials.map(t=>t.repeat))]);for(let id of ['case','mode','repeat'])$(id).onchange=init;for(let id of ['zoom','edges'])$(id).onchange=timeline;
let p='<table><tr><th>形状</th><th>模式</th><th>pair ms</th><th>IQR ms</th><th>tasks/s</th><th>相对 serial 配对变化</th></tr>',m='<table><tr><th>形状</th><th>模式</th><th>A ready ms</th><th>B ready ms</th><th>first / last ms</th><th>增量峰值 MiB</th></tr>';for(let r of D.summary.performance)for(let [mode,v] of Object.entries(r.modes)){let ms=x=>(x/1000).toFixed(2),valid=v.numerically_valid,tag=valid?'':' · 数值未通过';p+=`<tr class="${valid?'':'bad'}"><td>${r.case}</td><td>${mode+tag}</td><td>${ms(v.wall_us.median)}</td><td>${ms(v.wall_us.q1)}–${ms(v.wall_us.q3)}</td><td>${valid?v.tasks_per_second.median.toFixed(1):'不采纳'}</td><td>${valid&&mode!=='serial'?r.paired[mode].change_percent.median.toFixed(1)+'%':'—'}</td></tr>`;m+=`<tr><td>${r.case}</td><td>${mode+tag}</td><td>${ms(v.ready_us.A.median)}</td><td>${ms(v.ready_us.B.median)}</td><td>${ms(v.first_ready_us.median)} / ${ms(v.last_ready_us.median)}</td><td>${(v.incremental_peak.median/2**20).toFixed(1)}</td></tr>`}$('performance').innerHTML=p+'</table>';$('memory').innerHTML=m+'</table>';init();})().catch(e=>{document.getElementById('stats').textContent=String(e);throw e});</script></html>'''


def main():
    p=argparse.ArgumentParser();p.add_argument('graph',type=Path);p.add_argument('output',type=Path);a=p.parse_args()
    data=json.loads(a.graph.read_text());ids={n['id'] for n in data['nodes'] if n.get('trial')}
    view=dict(summary=data['summary'],nodes=[n for n in data['nodes'] if n['id'] in ids],
        edges=[e for e in data['edges'] if e['source'] in ids and e['target'] in ids],requirements=data['requirements'])
    a.output.parent.mkdir(parents=True,exist_ok=True)
    a.output.write_text(HTML.replace('__DATA__',base64.b64encode(gzip.compress(json.dumps(view,ensure_ascii=False,separators=(',',':')).encode(),mtime=0)).decode()))
    print(a.output,a.output.stat().st_size)


if __name__=='__main__':main()
