"""Generate a self-contained, offline browser for the actual MoE execution graph."""
import argparse,json
from pathlib import Path

HTML='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>P2 · MoE shared expert</title>
<style>body{margin:0;color:#183841;background:#f3f6f5;font:15px/1.65 system-ui,sans-serif}main{max-width:1260px;margin:auto;padding:30px 22px}h1{font-size:30px}h2{font-size:21px}section{background:white;border:1px solid #d5e1dc;border-radius:9px;padding:20px;margin:20px 0}label{display:inline-block;margin-right:12px;max-width:100%}select{font:inherit;padding:7px;max-width:100%}small{color:#566e77}.note{background:#fff3d9;padding:15px;border-left:4px solid #ba8739}.scroll{overflow:auto}svg{display:block}pre{max-height:350px;overflow:auto;white-space:pre-wrap;font-size:12px;background:#f1f5f3;padding:16px}table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:8px;border-bottom:1px solid #dae5de}.task,.stage{cursor:pointer}.task:hover{stroke:#111;stroke-width:2}a{color:#147e7a}.legend{display:flex;flex-wrap:wrap;gap:12px}.legend span:before{content:'●';color:var(--c);margin-right:5px}</style>
<main><small>PRACTICE 21 · ASCEND 910B2C · TP=1 · BF16 · EAGER</small><h1>同一次 forward 中的 MoE 分支与同步</h1><p>真实 Qwen2 MoE 层实现；确定性构造权重，8 个 routed expert，top-2，1 个 gated shared expert。选择形状、模式和重复编号，查看原始 kernel 与 event 的关联。</p><p class="note">本实验是缩小尺寸的真实模型层，不是预训练模型的端到端测试。数据边来自调用与张量边界，native kernel 内部 workspace 依赖仍未知。性能来自独立的无 profiler 测量；另有无方法观察器的轻量诊断对照，四种形状也未观察到计算重叠。</p>
<section><h2>实验选择</h2><label>token 数 <select id="tokens"></select></label><label>模式 <select id="mode"><option value="serial">serial · 同流</option><option value="parallel">parallel · 原生双流</option></select></label><label>重复 <select id="repeat"></select></label><p id="stats"></p><div id="legend" class="legend"></div></section>
<section><h2>分支数据 DAG</h2><div class="scroll" id="branch"></div><small>实线表示调用边界的数据要求；虚线表示额外的阶段调度约束。每条数据要求均在独立的 stream/event 同步图中检查可达性。点击阶段查看其实际 kernel。</small></section>
<section><h2>逐 kernel 执行图与设备时间线</h2><label>缩放 <select id="zoom"><option value="1">1×</option><option value="5">5×</option><option value="15">15×</option></select></label><label>连线 <select id="edges"><option value="event_wait">event wait</option><option value="data_dependency">数据边界</option><option value="stream_order">stream FIFO</option><option value="">隐藏连线</option></select></label><div class="scroll" id="timeline"></div><small>横轴为相对微秒；计算矩形采用实际设备时长，事件采用菱形符号。点击节点查看 host flow、CANN connection、CSV 行及依赖证据。另有 2 次跨流等待只有原生 API 证据，作为逻辑屏障保存在 JSON 中，不绘成设备任务。</small></section>
<section><h2>所选节点证据</h2><pre id="details">点击阶段或 kernel。</pre></section>
<section><h2>无 profiler 的完整层与独立分支耗时</h2><div class="scroll" id="performance"></div><small>单位 µs / call，显示中位数。完整层包含路由、shared gate、合并和原生同步；独立 routed 分支包含 router。独立分支之和不能直接替代完整层耗时。负值表示双流更快，配对比例不是统计显著性检验。</small></section>
<p><a href="../RESULTS.md">实测结论与复现范围</a> · <a href="../results/published/execution_graph.json">完整执行图 JSON</a></p></main>
<script>const DATA=__DATA__;
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),colors={input:'#697f8b',router:'#6876ac',routed:'#237f79',shared_up:'#c18735',shared_down:'#a96731',merge:'#895581'},labels={input:'共同输入',router:'router',routed:'routed experts',shared_up:'shared gate/up',shared_down:'shared act/down/gate',merge:'合并'};
const nodes=Object.fromEntries(DATA.nodes.map(n=>[n.id,n]));let selected;
function options(id,xs){$(id).innerHTML=xs.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function detail(x){$('details').textContent=JSON.stringify(x,null,2)}
function init(){selected=DATA.summary.trials.find(t=>t.tokens==$('tokens').value&&t.mode==$('mode').value&&t.repeat==$('repeat').value);if(!selected)return;$('stats').textContent=`${selected.compute_tasks} 个计算任务 · stream ${selected.streams.join(' / ')} · shared/routed 计算交叠 ${Number(selected.branch_overlap_us).toFixed(3)} µs · 输出一致`;branch();timeline()}
function branch(){const pos={input:[10,45],router:[220,15],routed:[455,15],shared_up:[220,160],shared_down:[455,160],merge:[760,80]};let svg='<svg width="990" height="255" viewBox="0 0 990 255"><defs><marker id="ba" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="#69868a"/></marker></defs>';
for(const e of DATA.requirements.filter(e=>e.trial==selected.id)){let a=pos[e.producer],b=pos[e.consumer];svg+=`<path d="M${a[0]+180} ${a[1]+26}L${b[0]} ${b[1]+26}" fill="none" stroke="#69868a" marker-end="url(#ba)"><title>${esc(e.producer)} → ${esc(e.consumer)} · HB ${e.satisfied}</title></path>`}
if(selected.mode==='parallel')svg+='<path d="M620 68L620 150" stroke="#b9782e" stroke-dasharray="4 3" marker-end="url(#ba)"/><text x="645" y="122" font-size="11">before_combine</text>';
for(const [stage,p] of Object.entries(pos)){let ts=selected.stages[stage].map(id=>nodes[id]);svg+=`<g class="stage" data-stage="${stage}"><rect x="${p[0]}" y="${p[1]}" width="180" height="56" rx="5" fill="${colors[stage]}"/><text x="${p[0]+7}" y="${p[1]+20}" fill="white" font-size="12">${labels[stage]}</text><text x="${p[0]+7}" y="${p[1]+40}" fill="white" font-size="11">${ts.length} kernels · stream ${[...new Set(ts.map(t=>t.stream))].join('/')}</text></g>`}svg+='</svg>';$('branch').innerHTML=svg;document.querySelectorAll('[data-stage]').forEach(e=>e.onclick=()=>detail({stage:e.dataset.stage,calls:DATA.records.filter(r=>r.trial===selected.id&&r.kind===e.dataset.stage),kernels:selected.stages[e.dataset.stage].map(id=>nodes[id]),requirements:DATA.requirements.filter(r=>r.trial===selected.id&&(r.producer===e.dataset.stage||r.consumer===e.dataset.stage))}))}
function timeline(){let ts=DATA.nodes.filter(n=>n.trial===selected.id&&n.kind==='device'&&n.stage!=='validation'),streams=[...new Set(ts.map(t=>t.stream))].sort(),low=Math.min(...ts.map(t=>Number(t.start_us))),high=Math.max(...ts.map(t=>Number(t.end_us))),span=high-low,width=1200*Number($('zoom').value),left=100,height=120+streams.length*100,coords={},out=`<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><defs><marker id="ta" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#6c699a"/></marker></defs>`;
streams.forEach((s,i)=>{let y=65+i*100;out+=`<text x="0" y="${y+18}" font-size="12">stream ${s}</text><line x1="100" x2="${width-30}" y1="${y+40}" y2="${y+40}" stroke="#d5dfda"/>`});
for(const t of ts){let x=left+(Number(t.start_us)-low)/span*(width-left-30),w=Number(t.duration_us)/span*(width-left-30),y=65+streams.indexOf(t.stream)*100;coords[t.id]=[x,y+15,w];}
let edges=$('edges').value==='data_dependency'?DATA.requirements:DATA.edges;for(const e of edges){if(e.kind!==$('edges').value||!coords[e.source]||!coords[e.target])continue;let a=coords[e.source],b=coords[e.target],x=a[0]+a[2];out+=`<path d="M${x} ${a[1]}C${x+12} ${a[1]-30} ${b[0]-12} ${b[1]-30} ${b[0]} ${b[1]}" stroke="#6c699a" stroke-width="1" fill="none" opacity=".7" marker-end="url(#ta)"><title>${esc(e.kind)}</title></path>`}
for(const t of ts){let [x,y,w]=coords[t.id],title=esc(t.name+' · '+t.duration_us+' µs · '+t.stage);out+=t.is_compute?`<rect class="task" data-task="${t.id}" x="${x}" y="${y-15}" width="${w}" height="30" fill="${colors[t.stage]||'#899e9a'}"><title>${title}</title></rect>`:`<path class="task" data-task="${t.id}" d="M${x} ${y-5}l4 5l-4 5l-4 -5Z" fill="#66777f"><title>${title}</title></path>`}
out+=`<text x="100" y="${height-15}" font-size="12">0 µs</text><text x="${width-125}" y="${height-15}" font-size="12">${span.toFixed(3)} µs</text></svg>`;$('timeline').innerHTML=out;document.querySelectorAll('[data-task]').forEach(e=>e.onclick=()=>detail({node:nodes[e.dataset.task],call:DATA.records.find(r=>r.label===nodes[e.dataset.task].scope),synchronization:DATA.edges.filter(x=>x.source===e.dataset.task||x.target===e.dataset.task),data:DATA.requirements.filter(x=>x.source===e.dataset.task||x.target===e.dataset.task)}))}
options('tokens',[...new Set(DATA.summary.trials.map(t=>t.tokens))]);options('repeat',[...new Set(DATA.summary.trials.map(t=>t.repeat))]);for(const id of ['tokens','mode','repeat'])$(id).onchange=init;for(const id of ['zoom','edges'])$(id).onchange=timeline;$('legend').innerHTML=Object.keys(colors).map(k=>`<span style="--c:${colors[k]}">${labels[k]}</span>`).join('');
let table='<table><tr><th>tokens</th><th>serial</th><th>parallel</th><th>shared only</th><th>routed only</th><th>配对变化中位数</th><th>双流更快的配对</th></tr>';for(const r of DATA.summary.performance)table+=`<tr><td>${r.tokens}</td>${['serial','parallel','shared_only','routed_only'].map(m=>`<td>${r.modes[m].median.toFixed(2)}</td>`).join('')}<td>${r.paired_change_percent.median.toFixed(1)}%</td><td>${r.parallel_faster_pairs}/${r.paired_change_percent.n}</td></tr>`;$('performance').innerHTML=table+'</table>';init();</script></html>'''


def main():
    p=argparse.ArgumentParser();p.add_argument('graph',type=Path);p.add_argument('output',type=Path);a=p.parse_args()
    data=json.loads(a.graph.read_text());a.output.parent.mkdir(parents=True,exist_ok=True)
    a.output.write_text(HTML.replace('__DATA__',json.dumps(data,ensure_ascii=False,separators=(',',':')).replace('</','<\\/')))
    print(a.output,a.output.stat().st_size)


if __name__=='__main__':main()
